### ISSUE TITLE
Replace network-client in by nano-api

### ISSUE THREAD

**Issue by Bettelstab** [nimiq/nano-api#3]
With core's new webYield functionality, it should not be necessary anymore to run the network connection in an iframe.

**Comment by danimoh** [comment]
The idea of the iframe was also that at some point consensus should only be established once in one iframe and then communicated to other network iframes in other windows / apps.
Might be not necessary anymore though with pico consensus.

**Comment by Bettelstab** [comment]
So instead we aim for https://github.com/nimiq/network/issues/5
